version: '3.5'

services:
  postgres:
    image: postgres:10.4
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: l5hscT2gzk4uUtpUR9vVse
      POSTGRES_DB: frontnode
      ALLOW_IP_RANGE: 0.0.0.0/0
    networks:
      - frontnode

networks:
  frontnode:
    name: frontnode
